export const piiCopy = {
  tr: {
    sectionTitle: 'Karşı taraf ödeme bilgileri',
    lockedTitle: 'Ödeme profili ve iletişim güvenli şekilde kilitli',
    lockedSub: 'Bilgileri yalnızca gerekli olduğunda doğrulayarak açın.',
    revealBtn: '🔓 Secure payment details göster',
    revealBtnLoading: 'Doğrulanıyor...',
    copyIban: '📋 IBAN Kopyala',
    copyRouting: '📋 Routing Kopyala',
    copyAccount: '📋 Hesap No Kopyala',
    copied: '✓ Kopyalandı',
    copyError: '⚠ Kopyalanamadı — manuel seçin',
    noSecureContext: '⚠ HTTP bağlantısı — ödeme bilgisini manuel kopyalayın',
    hideBtn: '🙈 Gizle',
    telegramBtn: 'Telegram Aç',
    emailBtn: 'E-posta Gönder',
    phoneBtn: 'Ara / Dialer Aç',
    disclaimer: '🔒 Şifreli kanal. Bilgileri açıkken ekran görüntüsü ve paylaşıma dikkat edin.',
    notice: 'Bu hassas bilgiler blockchain’e kaydedilmez; sadece bu işleme özel şifreli olarak iletildi.',
    loading: 'Yükleniyor...',
    noContact: 'İletişim bilgisi eklenmemiş',
    encryptedBadge: 'Uçtan uca şifreli',
    railPrefix: 'Rail',
    waitingTitle: 'Ödeme bekleniyor.',
    waitingSub: 'Karşı taraf ödeme profili ve iletişim bilgilerinizi şifreli kanaldan aldı.',
  },
  en: {
    sectionTitle: 'Secure payment details',
    lockedTitle: 'Payment profile and contact are securely locked',
    lockedSub: 'Reveal only when you need the details for this trade.',
    revealBtn: '🔓 Reveal secure payment details',
    revealBtnLoading: 'Verifying...',
    copyIban: '📋 Copy IBAN',
    copyRouting: '📋 Copy Routing',
    copyAccount: '📋 Copy Account',
    copied: '✓ Copied',
    copyError: '⚠ Copy failed — please select manually',
    noSecureContext: '⚠ HTTP connection — copy payment details manually',
    hideBtn: '🙈 Hide',
    telegramBtn: 'Open Telegram',
    emailBtn: 'Send Email',
    phoneBtn: 'Call / Open Dialer',
    disclaimer: '🔒 Encrypted channel. Be careful with screenshots and sharing while details are visible.',
    notice: 'Sensitive details are not stored on-chain. They were transmitted encrypted for this trade only.',
    loading: 'Loading...',
    noContact: 'No contact info provided',
    encryptedBadge: 'End-to-End Encrypted',
    railPrefix: 'Rail',
    waitingTitle: 'Waiting for fiat payment.',
    waitingSub: 'The counterparty received your payment profile and contact details through the encrypted channel.',
  },
};

export const getPiiCopy = (lang = 'tr') => piiCopy[String(lang || 'tr').toLowerCase()] || piiCopy.tr;

export default piiCopy;
